cards = {
    "spaAce": ["spades", "14"],
    "spa2": ["spades", "2"],
    "spa3": ["spades", "3"],
    "spa4": ["spades", "4"],
    "spa5": ["spades", "5"],
    "spa6": ["spades", "6"],
    "spa7": ["spades", "7"],
    "spa8": ["spades", "8"],
    "spa9": ["spades", "9"],
    "spa10": ["spades", "10"],
    "spaJ": ["spades", "11"],
    "spaQ": ["spades", "12"],
    "spaK": ["spades", "13"],
    "clubAce": ["clubs", "14"],
    "club2": ["clubs", "2"],
    "club3": ["clubs", "3"],
    "club4": ["clubs", "4"],
    "club5": ["clubs", "5"],
    "club6": ["clubs", "6"],
    "club7": ["clubs", "7"],
    "club8": ["clubs", "8"],
    "club9": ["clubs", "9"],
    "club10": ["clubs", "10"],
    "clubJ": ["clubs", "11"],
    "clubQ": ["clubs", "12"],
    "clubK": ["clubs", "13"],
    "heaAce":["hearts", "14"],
    "hea2":["hearts", "2"],
    "hea3":["hearts", "3"],
    "hea4":["hearts", "4"],
    "hea5":["hearts", "5"],
    "hea6":["hearts", "6"],
    "hea7":["hearts", "7"],
    "hea8":["hearts", "8"],
    "hea9":["hearts", "9"],
    "hea10":["hearts", "10"],
    "heaJ":["hearts", "11"],
    "heaQ":["hearts", "12"],
    "heaK":["hearts", "13"],
    "diaAce":["diamonds", "14"],
    "dia2":["", "2"],
    "dia3":["spades", "3"],
    "dia4":["spades", "4"],
    "dia5":["spades", "5"],
    "dia6":["spades", "6"],
    "dia7":["spades", "7"],
    "dia8":["spades", "8"],
    "dia9":["spades", "9"],
    "dia10":["spades", "10"],
    "diaJ":["spades", "11"],
    "diaQ":["spades", "12"],
    "diaK":["spades", "13"]
}
